method: "lstm_embedding"
graph: "swiss-1990"

verbose: 1  # verbosity level for ray tuner

# ray tuner settings:
num_samples: 200  # number of hyperparameter combinations to initialize the ray tuner with
# number of cpus to allocate to the ray tuner.
# - Non-positive values allocate all but that many cpus, e.g. -1 allocates all but 1 cpu. At least 1 cpu must be allocated.
# - Positive values allocate that many cpus. At most the number of available cpus can be allocated.
# - If None, use the default ray tuner behavior, which is to allocate all available cpus.
num_cpus: -2
storage_path: "swissrivernetwork/benchmark/outputs/ray_results/"  # directory to store ray tuner results relative to the root of the repository